# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4395c5b4995c61744a40d14c12c06c3e8b0329cf8ec62708a21eec9e715f78ab97984ed02937e5492276b49cfd9d539b22a1f6d1f28fbc2a9ac015a0fcf4c49

test:
  secret_key_base: 05bcc78760e7fb9c0cbc301e57bd85df163b90d5609a794ba6311e40a6783bba5a80c2b8c5d24e70422a3da6c2b311ea63bf7c390cd6776ec5b386b0d5812cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
