# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  #<<: *default
  adapter : postgresql
  host : ec2-54-221-225-242.compute-1.amazonaws.com
  username : txqhxwtlbejtan
  database : dc9icibbqdsuo
  port : 5432
  password: VRAyLU0PfCpXYJV33813U50HuR

production:
  adapter : postgresql
  host : ec2-54-221-225-242.compute-1.amazonaws.com
  username : txqhxwtlbejtan
  database : dc9icibbqdsuo
  port : 5432
  password: VRAyLU0PfCpXYJV33813U50HuR
